# Generated by Django 2.1.1 on 2018-09-19 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180919_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
