# Generated by Django 2.1.1 on 2018-09-20 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180919_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criado', to=settings.AUTH_USER_MODEL),
        ),
    ]
